[package]
name = "c2rust-bitfields-derive"
authors = ["C2Rust"]
version = "0.17.0"
publish = false
edition = "2018"
autobins = false

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[lib]
proc-macro = true
